config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  #get 'homes/index'
 #root to: redirect('/users/sign_in') # ログインページにリダイレクトする
  root 'lists#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Define nested resources for items within lists
  resources :lists do
    resources :items
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :items, only: [:create, :new, :index, :show, :edit, :update, :destroy]

  # GitHub認証のコールバックURLに対するルートを追加
  # devise_scope :user do
  #   get '/auth/github/callback', to: 'users/omniauth_callbacks#github'
  #   post '/auth/github', to: 'users/omniauth_callbacks#github'
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authorization.rb
class Authorization < ApplicationRecord
    belongs_to :user
  
    validates :uid, uniqueness: { scope: :provider }
  end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items, dependent: :destroy
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  validates :uid, uniqueness: { scope: :provider }

  def self.from_omniauth(auth)
    authorization = Authorization.find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    authorization.assign_attributes(name: auth.info.name, email: auth.info.email)

    where(email: auth.info.email).first_or_initialize.tap do |user|
      user.user_name = auth.info.name
      user.remote_profile_url = auth.info.image if auth.info.image.present?
      user.save!
      user.authorizations << authorization unless user.authorizations.exists?(provider: auth.provider, uid: auth.uid)
    end
  end

  has_many :authorizations, dependent: :destroy

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  def self.create_unique_string
    SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_list

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def create
    @item = @list.items.build(item_params)
    if @item.save
      redirect_to @list, notice: 'アイテムが作成されました'
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @list, notice: 'アイテムが更新されました'
    else
      render :edit
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @list = @item.list
    @item.destroy
  
    # Redirect to the list's details page with a 303 See Other status code
    redirect_to list_path(@list), status: :see_other, notice: 'アイテムが削除されました'
  end
  
  
  

  def show
    # リソースの詳細を表示するための処理を記述
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def index
    @lists = List.all
  end

  def show
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path, notice: 'リストが更新されました'
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other, notice: 'リストが削除されました'
  end
  

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # LINE ログイン用のコールバックアクションを定義
  def line
    basic_action
  end
  
  private

  # 基本的なアクションを定義
  def basic_action
    @omniauth = request.env["omniauth.auth"]
    if @omniauth.present?
      @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
      if @profile.email.blank?
        email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : "#{@omniauth["uid"]}-#{@omniauth["provider"]}@example.com"
        @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
      end
      @profile.set_values(@omniauth)
      sign_in(:user, @profile)
    end
    flash[:notice] = "ログインしました"
    redirect_to root_path
  end

  # 仮想メールアドレスを生成するメソッド
  def fake_email(uid, provider)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# ApplicationController を Devise::OmniauthCallbacksController に変更
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # 以下を追加
  def line
    basic_action
  end

  private

  def basic_action
    @omniauth = request.env["omniauth.auth"]
    if @omniauth.present?
      @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
      if @profile.email.blank?
        email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : fake_email(@omniauth["uid"], @omniauth["provider"])
        @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
      end
      @profile.set_values(@omniauth)
      sign_in(:user, @profile)
    end
    flash[:notice] = "ログインしました"
    redirect_to root_path
  end

  def fake_email(uid, provider)
    "#{uid}-#{provider}@example.com"
  end
  # 以上を追加
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash = {})
    hash[:uid] = User.maximum(:uid).to_i + 1
    super
  end

  def update_resource(resource, params)
    return super if params['password'].present?
  
    resource.update_without_password(params.except('current_password'))
  end
end

app/controllers/users/sessions_controller.rb
# app/controllers/users/sessions_controller.rb

class Users::SessionsController < Devise::SessionsController
    # カスタムアクションを追加したり、デフォルトのDeviseアクションをオーバーライドすることができます。
    def destroy
      reset_session
      redirect_to root_path, notice: 'ログアウトしました'
    end

  end

app/controllers/users/show.rb
module Users
    class Show
      # クラスの定義
    end
  end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      # インデックスアクションの中身は空でも構いません
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/items/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">編集する</h1>
      <%= form_with(model: [@list, @item], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :詳細 %>
          <%= form.text_field :name, class: "form-control text-center" %>
        </div>
        <!-- Descriptionフォームを削除 -->
        <div class="text-center">
          <%= form.submit "保存", class: "btn btn-primary" %>
         
          
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= link_to 'ログアウト', destroy_user_session_path, method: :get, data: { turbo_method: :delete } %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1>編集する</h1>
      <%= form_with(model: @list, local: true) do |form| %>
        <div class="form-group">
          <%= form.label :name, "リスト名", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= form.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= form.submit "保存", class: "btn btn-primary btn-block" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h1>ToDoリスト</h1>
  <div class="list-group">
    <% @lists.each do |list| %>
      <div style="line-height: 3;">
        <div class="list-group-item">
          <h5 class="mb-1"><%= link_to list.name, list_path(list) %></h5>
          <div class="d-flex justify-content-center"> <%= link_to '編集', edit_list_path(list), class: "btn btn-primary btn-sm" %>
            <%= form_tag list_path(list), method: :delete, data: { turbo_method: :delete, turbo_confirm: "このリストを削除してもよろしいですか？" } do %>
              <%= submit_tag "削除", class: "btn btn-danger btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="clearfix mt-3">
    <%= link_to 'ToDoリスト追加', new_list_path, class: "btn btn-yellow btn-sm mr-2" %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="list-form">
        <%= form_for @list, html: { class: "form" } do |form| %>
          <div class="form-group">
            <%= form.label :tOdo, class: "label" %>
            <%= form.text_field :name, class: "form-control text-field" %>
          </div>

          <div class="form-group">
            <%= form.submit "追加", class: "btn btn-primary submit-button" %>
          </div>
        <% end %>
        <%= link_to 'リスト一覧', lists_path, class: "btn btn-secondary list-link" %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= link_to "<<ToDoへ戻る", lists_path %>
<hr>
<div class="container text-center">
  <h2><%= @list.name %></h2>

  <hr>
  <% @list.items.each_with_index do |item, index| %>
    <div style="line-height: 3;">
      <%= "#{index + 1}. #{item.name}" %>
      <div class="d-flex justify-content-between">
        <%= link_to "編集", edit_list_item_path(@list, item), class: "btn btn-primary btn-sm" %>
        <%= form_tag list_item_path(@list, item), method: :delete, data: { turbo_method: :delete, turbo_confirm: "このアイテムを削除してもよろしいですか？" } do %>
          <%= submit_tag "削除", class: "btn btn-danger btn-sm" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <hr>
  <hr>
  <h1>詳細追加</h1>
  <%= form_for [@list, Item.new], html: { class: "text-center" } do |f| %>
    <%= f.text_field :name %> <%= f.submit "追加", class: "btn btn-success btn-sm mx-1" %>
    <br> <% end %>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome</title>
</head>
<body>
  <h1>Welcome to our application!</h1>
  <p>This is a sample welcome message.</p>
  <p>Feel free to explore the application.</p>
</body>
</html>